// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDggpV8MefEu3piOiLEuu2RfhvI7fr751I',
    appId: '1:128505410285:web:d2265348daeab8e0cd92e4',
    messagingSenderId: '128505410285',
    projectId: 'proyekshoes-f8b62',
    authDomain: 'proyekshoes-f8b62.firebaseapp.com',
    storageBucket: 'proyekshoes-f8b62.firebasestorage.app',
    measurementId: 'G-69MJJL0785',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtGfL7_VM7JIsi_aFEXD4gq_04_Y7dSOE',
    appId: '1:128505410285:android:a7bc08db9325d970cd92e4',
    messagingSenderId: '128505410285',
    projectId: 'proyekshoes-f8b62',
    storageBucket: 'proyekshoes-f8b62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1kwajH6ERyblUhHCK6Q00A8ws4qAeBos',
    appId: '1:128505410285:ios:5e8f2b6ec8962cddcd92e4',
    messagingSenderId: '128505410285',
    projectId: 'proyekshoes-f8b62',
    storageBucket: 'proyekshoes-f8b62.firebasestorage.app',
    iosBundleId: 'com.example.sepatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1kwajH6ERyblUhHCK6Q00A8ws4qAeBos',
    appId: '1:128505410285:ios:5e8f2b6ec8962cddcd92e4',
    messagingSenderId: '128505410285',
    projectId: 'proyekshoes-f8b62',
    storageBucket: 'proyekshoes-f8b62.firebasestorage.app',
    iosBundleId: 'com.example.sepatu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDggpV8MefEu3piOiLEuu2RfhvI7fr751I',
    appId: '1:128505410285:web:c8db5d305025cbfbcd92e4',
    messagingSenderId: '128505410285',
    projectId: 'proyekshoes-f8b62',
    authDomain: 'proyekshoes-f8b62.firebaseapp.com',
    storageBucket: 'proyekshoes-f8b62.firebasestorage.app',
    measurementId: 'G-9BYY1HRQYY',
  );
}
